#!/usr/bin/env python2.6

from optparse import OptionParser
import sys

from httpdmultiuser.commands import commands


if __name__ == '__main__':
    usage = "usage: %%prog {%s} args" % "|".join(commands)
    parser = OptionParser(usage=usage)
    options, args = parser.parse_args(args=sys.argv[1:2])
    
    try:
        cmd = args[0]
    except IndexError:
        parser.error("No command given")
    else:
        commands[cmd](*sys.argv[2:])
